on:
  push:
    branches:
      - main
    paths:
      - src/services/checkout/**
name: checkout service containerization

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          containerName: checkout
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$containerName:${{ github.sha }} -f ./src/service/checkout/Dockerfile
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$containerName:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.AZURE_RG }}
            dns-name-label: ${{ secrets.AZURE_RG }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/$containerName:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-$containerName
            location: 'west europe'