on: [push]
name: Bicep deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./provision/dapr.bicep
        parameters: 
          environment_name=containerEnv
          acrName=Dir4CbSlSkGyVEPdh8kd5w
          location=west-europe
          storage_account_name=dapraca23948394
          storage_container_name=state
        failOnStdErr: false
